services:
  vision:
    image: ultralytics/ultralytics:latest-jetson-jetpack6
    container_name: truevalue_vision
    environment:
      PROPERTY: ${PROPERTY:-1}
      NODE: ${NODE:-1}
      BASE_URL: ${BASE_URL:-http://192.168.50.115:8000}
      SHOW_VIDEO: ${SHOW_VIDEO:-false}
    ipc: host
    runtime: nvidia
    volumes:
      - ../edge/vision:/app/vision